services:
  - type: web
    name: agenda-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: RENDER_URL
        value: https://proyecto1-rmtf.onrender.com
